/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.me.androidkvb;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int logo=0x7f020000;
    }
    public static final class id {
        public static final int barnow=0x7f06000a;
        public static final int bartol=0x7f060009;
        public static final int button=0x7f060003;
        public static final int console=0x7f06000c;
        public static final int logo=0x7f060007;
        public static final int mainpanel=0x7f060000;
        public static final int processbar=0x7f060004;
        public static final int pwd=0x7f060002;
        public static final int sid=0x7f060001;
        public static final int widget0=0x7f060008;
        public static final int widget32=0x7f06000b;
        public static final int widget33=0x7f060005;
        public static final int widget34=0x7f060006;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int process=0x7f030001;
    }
    public static final class raw {
        public static final int kb=0x7f040000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
    }
}
