package net._3haku.kvb.db;



/**
 * Productlock generated by hbm2java
 */
public class Productlock  implements java.io.Serializable {


     private Integer id;
     private String pstring;
     private int uid;

    public Productlock() {
    }

    public Productlock(String pstring, int uid) {
       this.pstring = pstring;
       this.uid = uid;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getPstring() {
        return this.pstring;
    }
    
    public void setPstring(String pstring) {
        this.pstring = pstring;
    }
    public int getUid() {
        return this.uid;
    }
    
    public void setUid(int uid) {
        this.uid = uid;
    }




}


